# Generated by Django 5.2.15 on 2026-07-20 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_program_programgallery_programreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, default='#4F46E5', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Category',
                'verbose_name_plural': 'Program Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-created_at'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='programbeneficiary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Program Beneficiary', 'verbose_name_plural': 'Program Beneficiaries'},
        ),
        migrations.AlterModelOptions(
            name='programgallery',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='programreport',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='beneficiaries_target',
            new_name='beneficiary_count',
        ),
        migrations.RenameField(
            model_name='programbeneficiary',
            old_name='enrolled_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='programreport',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AlterUniqueTogether(
            name='programbeneficiary',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='program',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='program',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='program',
            name='location',
        ),
        migrations.RemoveField(
            model_name='programreport',
            name='report',
        ),
        migrations.AddField(
            model_name='program',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='core.country'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='expected_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='funding_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_programs', to='core.state'),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programbeneficiary',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programbeneficiary',
            name='community',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='programbeneficiary',
            name='disability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programbeneficiary',
            name='full_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programbeneficiary',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='programbeneficiary',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programbeneficiary',
            name='occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='programbeneficiary',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='programbeneficiary',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programgallery',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_program_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programreport',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programreport',
            name='lessons_learned',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programreport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_program_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programreport',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='programgallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='core.programcategory'),
        ),
        migrations.CreateModel(
            name='ProgramDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('report', 'Report'), ('proposal', 'Proposal'), ('budget', 'Budget'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='programs/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.program')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_program_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='programbeneficiary',
            name='member',
        ),
        migrations.CreateModel(
            name='ProgramVolunteerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_program_volunteers', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='core.program')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_assignments', to='core.volunteer')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('program', 'volunteer')},
            },
        ),
    ]
