# Generated by Django 5.2.15 on 2026-07-20 11:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_programcategory_alter_program_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='volunteerhourlog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='volunteerhourlog',
            name='activity_date',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_volunteers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_volunteers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-()]{7,15}$', message='Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/photos/'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_volunteers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerhourlog',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerhourlog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_volunteer_hours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteerhourlog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerhourlog',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_hour_logs', to='core.program'),
        ),
        migrations.AddField(
            model_name='volunteerhourlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='programgallery',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='programreport',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('weekends', 'Weekends'), ('remote', 'Remote'), ('on_call', 'On Call')], default='full_time', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_profile', to='core.member'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerhourlog',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VolunteerCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='volunteers/certificates/')),
                ('issue_date', models.DateField()),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.volunteer')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication', models.PositiveIntegerField(default=0)),
                ('teamwork', models.PositiveIntegerField(default=0)),
                ('leadership', models.PositiveIntegerField(default=0)),
                ('punctuality', models.PositiveIntegerField(default=0)),
                ('professionalism', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_evaluations', to='core.program')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.volunteer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='volunteer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='core.volunteerskill'),
        ),
        migrations.CreateModel(
            name='VolunteerTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='volunteers/trainings/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='core.volunteer')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_attendance', to='core.program')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.volunteer')),
            ],
            options={
                'ordering': ['-attendance_date'],
                'unique_together': {('volunteer', 'program', 'attendance_date')},
            },
        ),
    ]
