# Generated by Django 5.2.15 on 2026-09-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_volunteer_last_gps_at_volunteer_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programgallery',
            name='published',
            field=models.BooleanField(default=True, help_text='Show this photo and caption on the public program page.'),
        ),
    ]
