# Generated by Django 5.2.15 on 2026-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_programgallery_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional lead image shown with the story on the website.', null=True, upload_to='news/covers/'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
