# Generated by Django 5.2.15 on 2026-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newspost_cover_image_newspost_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='programreport',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programreport',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='programreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('published', 'Published')], db_index=True, default='draft', max_length=20),
        ),
    ]
